name: 💡 General Feature Request

description: Have a new idea/feature for docs? Please suggest!

title: '[FEATURE] <description>'

labels: ['⭐ goal: addition']

body:

  - type: textarea

    id: description

    attributes:

      label: Description

      description: A brief description of the enhancement you propose, also include what you tried and what worked.

    validations:

      required: true

  - type: textarea

    id: screenshots

    attributes:

      label: Screenshots

      description: Please add screenshots if applicable

    validations:

      required: false

  - type: textarea

    id: extrainfo

    attributes:

      label: Additional information

      description: Is there anything else we should know about this idea?

    validations:

      required: false

  - type: markdown

    attributes:

      value: 
        Feel free to check out other cool repositories of the daily.dev Community [here](https://github.com/dailydotdev)
